### ISSUE TITLE
Create an issue

### ISSUE THREAD

**Issue by mannuelf** [cameronmoodley/builders-repo#1]

**Comment by cameronmoodley** [comment]
Hey Manny

Cool man so this is basically just an empty frame that we can add on to if there is anything cool you can think off that you want to add to this template buddy go for it. I did some forms at work last week I think that maybe a good place to start if you can create a simple form Ive added in the routing for that so you can just start developing but check out angular 2 form builder.

I am going to start writing a service that displays in the front end, using this website I just want to see if I can connect to this website http://www.jsontest.com/ VIA a service and display it on the front end.

**Comment by mannuelf** [comment]
Hey @cameronmoodley ya bru excited check out this cool list of API's we can play with https://github.com/toddmotto/public-apis
